---
- name: copy kuala-frontend files
  copy:
    src: ../files/kuala-frontend
    dest: /opt

- name: deploy/restart kuala-frontend apps 
  community.docker.docker_compose_v2:
    project_src: /opt/kuala-frontend
    files: 
      - "docker-compose.yaml"
    state: present
  environment:
    DOCKER_BUILDKIT: "1"
    COMPOSE_DOCKER_CLI_BUILD: "1"
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
