name: Run kuala-frontend playbook
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ansible/roles/kuala-frontend/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run kuala-frontend playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook/kuala-frontend.yaml
          directory: ./ansible
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          requirements: ./requirements.yml
          options: |
            -i inventory/base.ini
            --verbose        
            --tags=kuala-frontend
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
