name: Run kuala-frontend playbook
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ansible/roles/kuala-frontend/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Verify submodule content
        run: |
          ls -R submodules/kuala-frontend/

      - name: Ensure webapps directory exists
        run: mkdir -p ansible/roles/kuala-frontend/files/kuala/volumes/functions/

      - name: Copy kuala-api functions to kuala ansible role
        run: |
          cp -r submodules/kuala-frontend/webapps/functions/* ansible/roles/kuala/files/kuala/volumes/functions/

      - name: Copy deno.json to kuala ansible role
        run: |
          cp submodules/kuala-api/supabase/functions/deno.json ansible/roles/kuala/files/kuala/volumes/functions/kuala/

      - name: Run kuala playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook/kuala-frontend.yaml
          directory: ./ansible
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          requirements: ./requirements.yml
          options: |
            -i inventory/base.ini
            --verbose        
            --tags=kuala
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
